extends: eslint:recommended
plugins:
  - import
env:
  mocha: true
  commonjs: true
  es6: true
  node: true
globals:
  assert: true
  stub: true
  spy: true
  createStubInstance: true
  useFakeTimers: true
parserOptions:
  ecmaversion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  strict: off
  no-console: off
